--데이터 추가 , 수정 , 삭제

--1)테이블에 데이터를 추가하는 insert문
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP;
--DEPT_TEMP 테이블 생성 
INSERT INTO DEPT_TEMP(DEPTNO , DNAME , LOC)
VALUES (50,'DATABASE' , 'SEOUL');
-- 값 추가 DEPTNO = 50 , DNAME = DATABASE , LOC = SEOUL
SELECT * FROM DEPT_TEMP;
INSERT INTO DEPT_TEMP
VALUES (60 , 'NETWORK', 'BUSAN');
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (70 , 'WEB', NULL);
INSERT INTO DEPT_TEMP (DEPTNO, DNAME , LOC)
VALUES (80 , 'MOBILE', '');
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
VALUES (90 , 'INCHEON');

--테이블에 NULL 데이터 입력하기
CREATE TABLE EMP_TEMP
AS SELECT *
FROM EMP
WHERE 1 <> 1;
SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
)
VALUES (1111, '성춘향', 'MANAGER', 9999, '2001-01-05', 4000, NULL, 20);
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR , HIREDATE, SAL , COMM, DEPTN
O)
VALUES (2111, '이순신', 'MANAGER', 9999, '07/01/2001', 4000, NULL, 20);
SELECT * FROM EMP_TEMP

--테이블에 날짜 데이터 입력하기 -> 직접입력 , TO_DATE , SYSDATE 이용
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
)
VALUES (2111, '이순신', 'MANAGER', 9999, 
TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
)
VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);
SELECT * FROM EMP_TEMP;

--서브쿼리를 사용해 한번에 여러 데이터 추가
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 1;
SELECT * FROM EMP_TEMP;
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP2;

--UPDATE 문
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';
-- DEPT_TEMP2 테이블의 모든행 LOC값을 SEOUL로 변경
SELECT * FROM DEPT_TEMP2;
ROLLBACK; --업데이트 취소 COMMIT하기 전까진 되돌릴 수 있음

--데이터 일부분 수정
UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE', LOC = 'SEOUL'
WHERE DEPTNO = 40;

--서브쿼리를 이용해 데이터 수정
UPDATE DEPT_TEMP2
SET (DNAME,LOC) = (SELECT DNAME , LOC FROM DEPT WHERE DEPTNO =40)
WHERE DEPTNO = 40;

UPDATE DEPT_TEMP2
SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40),
LOC = (SELECT LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

--DELETE문
--데이터 일부분만 삭제하기
DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

--서브쿼리를 이용해 데이터삭제
DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO FROM EMP_TEMP2 E,SALGRADE s
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 3
AND DEPTNO = 30);

--데이터 삭제
DELETE FROM EMP_TEMP2;




















