--테이블 생성
CREATE TABLE SHOP_PRODUCT (
PROD_ID NUMBER(4) PRIMARY KEY,
PROD_NAME VARCHAR2(50) NOT NULL,
CATEGORY VARCHAR2(20),
PRICE NUMBER(10) CONSTRAINT TBLCK_PRICE CHECK(PRICE > 0),
STOCK NUMBER(5),
REG_DATE DATE DEFAULT SYSDATE); 

--테이블 값 입력
INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(1,'SSA','가전',550000,11,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(2,'SSB','생활',450000,15,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(3,'SSC','가전',450000,16,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(4,'SSD','전자',550000,13,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(5,'SSE','가전',450000,7,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(6,'AAQ','전자',450000,6,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(7,'AAW','가전',550000,5,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(8,'AAE','전자',550000,11,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(9,'AAS','전자',450000,11,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(10,'AAT','생활',450000,8,TO_DATE(SYSDATE,'YYYY/MM/DD')); 

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(11,'AAS','생활',480000,8,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(12,'BBA','전자',570000,9,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(13,'BBB','가전',600000,10,TO_DATE(SYSDATE,'YYYY/MM/DD'));

INSERT INTO SHOP_PRODUCT(PROD_ID,PROD_NAME,CATEGORY,PRICE,STOCK,REG_DATE)
VALUES(14,'BBC','용품',400000,11,TO_DATE(SYSDATE,'YYYY/MM/DD'));

--모든 상품의 이름, 카테고리, 단가를 조회하되 단가가 높은 순으로 정렬하시오.
SELECT PROD_NAME AS "이름",
CATEGORY AS "카테고리",
PRICE AS "단가"
FROM SHOP_PRODUCT
ORDER BY PRICE DESC;

--카테고리별 '평균 단가'를 계산하여 출력하되, 평균 단가가 500,000원 이상인 곳만 조회하시오.
SELECT CATEGORY AS "카테고리",
PRICE AS "단가"
FROM SHOP_PRODUCT
GROUP BY CATEGORY , PRICE
HAVING AVG(PRICE) >=500000
ORDER BY CATEGORY;

--전체 상품의 평균 단가보다 높은 단가를 가진 상품의 이름과 단가를 조회하시오.
SELECT PROD_NAME AS "상품명",
PRICE AS "단가"
FROM SHOP_PRODUCT
WHERE PRICE > (SELECT AVG(PRICE) FROM SHOP_PRODUCT); 

--'가전' 카테고리 상품 중 재고가 10개 미만인 상품의 단가를 10% 인상하시오.
UPDATE SHOP_PRODUCT
SET PRICE = PRICE * 1.1
WHERE CATEGORY = '가전' AND STOCK <10 ;

--상품명이 'S'로 시작하거나 카테고리가 '생활'인 상품의 모든 정보를 조회하시오.
SELECT PROD_ID AS "상품 번호",
PROD_NAME AS "이름",
CATEGORY AS "카테고리",
PRICE AS "단가",
STOCK AS "재고 수량",
REG_DATE AS "등록일"
FROM SHOP_PRODUCT
WHERE PROD_NAME LIKE 'S%' OR CATEGORY = '생활';

 --프로시저
CREATE OR REPLACE PROCEDURE PROC_ADD_PRICE(
p_id IN OUT NUMBER,
p_amount IN OUT NUMBER) 
IS
BEGIN
DBMS_OUTPUT.PUT_LINE('p_id : ' || p_id);
DBMS_OUTPUT.PUT_LINE('p_amount : ' || p_amount);
UPDATE SHOP_PRODUCT SET PRICE = PRICE + p_amount WHERE p_id = PROD_ID;
COMMIT;
END PROC_ADD_PRICE;

--트리거
/* 테이블 생성
CREATE TABLE DEL_LOG (
P_ID NUMBER(4),
DEL_DATE DATE); */

CREATE OR REPLACE TRIGGER shop_prod_del_log
AFTER
INSERT OR UPDATE OR DELETE ON SHOP_PRODUCT
FOR EACH ROW
BEGIN
IF DELETING THEN
INSERT INTO SHOP_PRODUCT
VALUES ('SHOP_PRODUCT','DELETE', :OLD.PROD_ID, SYSDATE);
ELSIF INSERTING THEN
INSERT INTO DEL_LOG
VALUES('SHOP_PRODUCT','INSERT', :NEW.PROD_ID,SYSDATE);
END IF;
END;